name: testing on PR to main
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
jobs:
  validate-npm-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: npm
          cache-dependency-path: package-lock.json
          registry-url: 'https://registry.npmjs.org'
      - name: can npm publish?
        run: npx can-npm-publish
